### ISSUE TITLE
Debugging node.js project: Error running <Configuration>: Connection refused

### ISSUE THREAD

**Issue by sbrunov** [consulo/consulo-nodejs#2]
Hello!

Currently working on a node.js project using Consulo 1.0.1227 and getting the following error when trying to start the debugger:

    Error running <Configuration>: Connection refused

A part of the log file:

    2015-12-04 12:07:21,126 [90282780]   INFO - tion.impl.ExecutionManagerImpl - Connection refused 
    com.intellij.execution.ExecutionException: Connection refused
        at org.mustbe.consulo.javascript.run.debug.V8DebugProcess.<init>(V8DebugProcess.java:97)
        at org.mustbe.consulo.nodejs.run.NodeJSDebuggerRunner$1.start(NodeJSDebuggerRunner.java:68)
        at com.intellij.xdebugger.impl.XDebuggerManagerImpl.startSession(XDebuggerManagerImpl.java:219)
        at com.intellij.xdebugger.impl.XDebuggerManagerImpl.startSession(XDebuggerManagerImpl.java:181)
        at org.mustbe.consulo.nodejs.run.NodeJSDebuggerRunner.doExecute(NodeJSDebuggerRunner.java:61)
        at com.intellij.execution.runners.GenericProgramRunner$1.execute(GenericProgramRunner.java:42)
        at com.intellij.execution.impl.ExecutionManagerImpl$2.run(ExecutionManagerImpl.java:210)
        at com.intellij.openapi.project.DumbServiceImpl.runWhenSmart(DumbServiceImpl.java:149)
        at com.intellij.execution.impl.ExecutionManagerImpl$1$1.run(ExecutionManagerImpl.java:176)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
        at java.awt.EventQueue.access$300(EventQueue.java:103)
        at java.awt.EventQueue$3.run(EventQueue.java:706)
        at java.awt.EventQueue$3.run(EventQueue.java:704)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:77)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
        at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:843)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:644)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:380)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
    Caused by: java.net.ConnectException: Connection refused
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:579)
        at org.chromium.sdk.internal.transport.AbstractSocketWrapper.<init>(AbstractSocketWrapper.java:33)
        at org.chromium.sdk.internal.transport.SocketWrapper.<init>(SocketWrapper.java:27)
        at org.chromium.sdk.internal.transport.SocketConnection.attach(SocketConnection.java:288)
        at org.chromium.sdk.internal.transport.SocketConnection.start(SocketConnection.java:443)
        at org.chromium.sdk.internal.standalonev8.StandaloneVmImpl.attachImpl(StandaloneVmImpl.java:120)
        at org.chromium.sdk.internal.standalonev8.StandaloneVmImpl.attach(StandaloneVmImpl.java:78)
        at org.mustbe.consulo.javascript.run.debug.V8DebugProcess.<init>(V8DebugProcess.java:93)
        ... 25 more

Best regards,
Sergey Brunov.

**Comment by VISTALL** [comment]
Can you can NodeJS build & OS.

Thanks

**Comment by sbrunov** [comment]
Here is the basic information about the environment:

    2015-12-04 12:51:19,653 [      9]   INFO -        #com.intellij.idea.Main - IDE: Consulo (build #1235, 04 Dec 2015 01:00) 
    2015-12-04 12:51:19,653 [      9]   INFO -        #com.intellij.idea.Main - OS: Linux (3.16.0-4-amd64, amd64) 
    2015-12-04 12:51:19,653 [      9]   INFO -        #com.intellij.idea.Main - JRE: 1.7.0_91-b02 (Oracle Corporation) 
    2015-12-04 12:51:19,653 [      9]   INFO -        #com.intellij.idea.Main - JVM: 24.91-b01 (OpenJDK 64-Bit Server VM) 
    2015-12-04 12:51:19,656 [     12]   INFO -        #com.intellij.idea.Main - JVM Args: -Xms512m -Xmx1500m -XX:MaxPermSize=512m -XX:ReservedCodeCacheSize=128m -ea -Dsun.io.useCanonCaches=false -Djava.net.preferIPv4Stack=true -XX:+UseCodeCacheFlushing -XX:+UseConcMarkSweepGC -XX:SoftRefLRUPolicyMSPerMB=50 -XX:+HeapDumpOnOutOfMemoryError -Dawt.useSystemAAFontSettings=lcd -Djb.vmOptionsFile=/opt/consulo/bin/consulo64.vmoptions -Xbootclasspath/a:/opt/consulo/bin/../lib/boot.jar -Djb.restart.code=88 
    2015-12-04 12:51:19,670 [     26]   INFO -        #com.intellij.idea.Main - JNA library loaded (64-bit) in 14 ms 
    ...
    2015-12-04 12:51:20,312 [    668]   INFO - llij.ide.plugins.PluginManager - 5 plugins initialized in 368 ms 
    2015-12-04 12:51:20,312 [    668]   INFO - llij.ide.plugins.PluginManager - Loaded bundled plugins: IDEA CORE (1235) 
    2015-12-04 12:51:20,312 [    668]   INFO - llij.ide.plugins.PluginManager - Loaded custom plugins: JavaScript (1438), NodeJS (1242), XML (1612) 

The version of node.js is 4.2.2. Also, [nvm](https://github.com/creationix/nvm) is used to have multiple node.js versions. So, Consulo IDE has the `node.js home path` set to `<User home>/.nvm/versions/node/v4.2.2/bin`.

Best regards,
Sergey Brunov.

**Comment by VISTALL** [comment]
Can you show command line of process? You can saw it log tab

![](http://klikr.org/cf3bd4a8b6c621ad779efa27839b.png)

**Comment by sbrunov** [comment]
The "Debug" tool window can not be shown (the appropriate menu item, `View => Tool Windows => Debug`, is disabled) for some reason: it seems the debugger "returns" immediately right after entering debug mode. So, the "Console" tab could not be found.

![20151204_consulo_nodejs_connection_refused](https://cloud.githubusercontent.com/assets/3449295/11588588/b8c9cb22-9a4f-11e5-9a40-57fef17d78e2.png)

Best regards,
Sergey Brunov.

**Comment by VISTALL** [comment]
Hm. 'Unnamed' run configuration is NodeJS ?(green icon)

**Comment by VISTALL** [comment]
Reproduced

**Comment by VISTALL** [comment]
I added some fix, it dont fix all issues, but you can run now in Debug mode

**Comment by sbrunov** [comment]
@VISTALL, thank you very much!
Have just checked the updated version: it works just fine!

Best regards,
Sergey Brunov.

**Comment by VISTALL** [comment]
yeah - it can be :) Its very poor debugger for now

**Comment by VISTALL** [comment]
added stepping

**Comment by sbrunov** [comment]
@VISTALL, great! Thank you!
Have just checked the updated version: the "Step over" functionality is supported.

Best regards,
Sergey Brunov.

**Comment by VISTALL** [comment]
Thanks!
